import star from "@/public/star.svg";
import starFish from "@/public/starFish.svg";
import StarBox from "@/public/StarBox.svg";
import smile from "@/public/smile.svg";
import lightBulb from "@/public/lightBulb.svg";
import ImageBox from "@/public/ImageBox.svg";
import FrameLayout from "@/public/FrameLayout.svg";
import instaIcon from "@/public/instaIcon.svg";
import twitter from "@/public/twitter.svg";
import ball from "@/public/ball.svg";
import NewText from "@/public/NewText.svg";
import TopRightArrow from "@/public/TopRightArrow.svg";
import BlueCircleStar from "@/public/HashCircle.svg";
import HeartCircle from "@/public/HeartCircle.svg";
import HashCircle from "@/public/HashCircle.svg";
import DownCircle from "@/public/DownCircle.svg";
import Hamburger from "@/public/Hamburger.svg";
import YellowStar from "@/public/HashCircle.svg";
import RightArrow from "@/public/rightArrow.svg";
import LeftArrow from "@/public/leftArrow.svg";
import SpeakingEffect from "@/public/SpeakingEffect.svg";

export const StarIcon = star;
export const BallIcon = ball;
export const NewTextIcon = NewText;
export const DownCircleIcon = DownCircle;
export const HamburgerIcon = Hamburger;
export const HashCircleIcon = HashCircle;
export const SpeakingEffectIcon = SpeakingEffect;
export const YellowStarIcon = YellowStar;
export const BlueCircleStarIcon = BlueCircleStar;
export const HeartCircleIcon = HeartCircle;
export const StarFishIcon = starFish;
export const TopRightArrowIcon = TopRightArrow;
export const RightArrowIcon = RightArrow;
export const LeftArrowIcon = LeftArrow;
export const StarBoxIcon = StarBox;
export const SmileIcon = smile;
export const LightBulbIcon = lightBulb;
export const TwitterIcon = twitter;
export const InstagramIcon = instaIcon;
export const ImageBoxIcon = ImageBox;
export const FrameLayoutIcon = FrameLayout;
